### ISSUE TITLE
Convention for giving a title to a document?

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#1]
What will be the convention on naming the document? This might be what appears in search results.

In the example, I've based it of the series as described in Paul's stylebook but added the regnal year. If we refer to _The National Archives_ should it be disambiguated, e.g. 'The National Archives, Kew'? 

Example title:

```
<title>Receipt Roll of the Irish Exchequer for 29 and 30 Edward I (The National Archives, E 101)</title>
```

See https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-titleStmt.html
See https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-title.html

**Comment by crooksp** [comment]
I imagine we will use the title from the Discovery Catalogue for the roll in question, which should in turn become the title in the ISAD(G) statement for the record.

**Comment by pdryburgh** [comment]
We should use the Discovery description where appropriate, I agree. It may be we are able to add our own amendments or revisions upon detailed analysis - Discovery can always be changed!

**Comment by MikeJ1971** [comment]
Ok, using the Description in the CSV file sent by Paul, the title for the example would change from ...

```<title>Receipt Roll of the Irish Exchequer for 29 and 30 Edward I (The National Archives, E 101)</title>```

to ...

```<title>Roll of receipts. 29 and 30 Edw I 18 membranes.</title>```

Does this give enough details/context?

**Comment by MikeJ1971** [comment]
Membranes should be in the extent.

**Comment by MikeJ1971** [comment]
We will go with:

```<title>Receipt Roll of the Irish Exchequer for 29 and 30 Edward I</title>```

Needs further discussion on dates and their representation.

**Comment by MikeJ1971** [comment]
Ok, I think we agreed to use Discovery as a basis, but with the option to amend or provide a more meaningful or descriptive title. In the case of the example, we've gone with:

```
         <titleStmt>
            <title>Receipt roll of the Irish Exchequer for 29 and 30 Edward I (The National
               Archives, E 101/233/16)</title>
         </titleStmt>
```

**Comment by crooksp** [comment]
hi Mike, 

I am worried that we are mixing up here the Title and Reference Code. I would prefer if the title was in the form "Receipt roll of the Irish Exchequer for 29 and 30 Edward I", and we keep the reference code "The National Archives, E 101/233/16" distinct. 

The reason for this is to future proof. If we were, in the future, doing a TEI edition of a Memoranda Roll, there would be no original, so the Title would be "Memoranda roll of the Irish Exchequer for 29 and 30 Edward I", but there could be multiple replacement sources whose reference codes would need to be included. 

Does that make any sense? 

Peter

**Comment by MikeJ1971** [comment]
Of course. I think I misunderstood. I'll fix that now.

**Comment by crooksp** [comment]
No problem -- this bit of conceptualization is the hardest thing to imagine in the abstract, and I am still working it out. At the next step, let's involve Gary to check our logic and choices.

**Comment by MikeJ1971** [comment]
I've updated the example.

**Comment by munnellg** [comment]
Just to be clear, there's nothing wrong with putting the reference code in the title if you like, but the database won't know to look for it there. If you want to fetch manuscript E 101, then this code must appear in the reference code DB database table.

That being said, for display purposes, you may like to have the reference code in the title. But that is entirely up to what you want to see in a title field when rendering a document on a web page. Of course, we can automatically append a reference code to the title if both are in the DB.
