### ISSUE TITLE
Which languages?

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#10]
The <langUsage> tag allows us to 'describes the languages, sublanguages, registers, dialects, etc. represented within a text'. I think this refers to the electronic version we are creating and, often, this will be an English-language translation of the source material. However, I'm guessing certain words from the original will be encoded if they are of particular interest or the translation is uncertain?

```
         <langUsage>
            <language ident="eng">English</language>
            <language ident="enm">English, Middle (1100–1500)</language>
            <language ident="lat">Latin</language>
            <language ident="gle">Irish</language>
            <language ident="mga">Irish, Middle (900–1200)</language>
            <language ident="fro">French, Old (842–ca. 1400)</language>
         </langUsage>
```

Note: I need to check the language codes as there are several.

See https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-langUsage.html

**Comment by crooksp** [comment]
Yes, I think we could usefully clarify this in the sense of specifying an English-language calendar of Latin (and sometimes French and Middle English original material). 

It would be worth thinking through some other examples of how this could play out with other Beyond 2022 materials.

**Comment by MikeJ1971** [comment]
Can we show the original versus the translation?

**Comment by crooksp** [comment]
Advice is to treat 'language' as a description of the language of the original, unless we can specify edition versus the original

**Comment by MikeJ1971** [comment]
Ok. In the **profileDesc** I've gone for English, since that is the language in the encoded edition:

```         
         <langUsage>
            <language ident="eng">English</language>
         </langUsage>
```

However, we describe in **msContents** under the **sourceDesc** that the original document was mainly Latin:

```
               <msContents>
                  <textLang mainLang="la">Latin</textLang>
               </msContents>
```

Does this seem like a reasonable solution @crooksp ?

**Comment by crooksp** [comment]
That seems very helpful -- and for our own internal documentation, we can record taht <langUsage> refers to the edition always (it could be an edition using original source language), whereas <textLang> is always the original source language. 

What happens if these are the same? Does one become redundant? 

Anyway you have a solution here for present purposes.
