### ISSUE TITLE
Notes on sourceDesc

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#12]
The _Source Description_ 'describes the source(s) from which an electronic text was derived or generated ...'. For me, that means describing the source of a translation, transcription or calendar. See https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-sourceDesc.html

This allows us to use a 'Manuscript Description', where we can say where original is stored, its identifier and some details about its composition and language. There are lots of options here: https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-msDesc.html

```
         <sourceDesc>
            <msDesc>
               <msIdentifier>
                  <settlement>London</settlement>
                  <repository>The National Archives</repository>
                  <idno>E 101/233/16</idno>
                  <msName>Roll of receipts. 29 and 30 Edward I.</msName>
               </msIdentifier>
               <msContents>
                  <textLang>Latin</textLang>
               </msContents>
               <physDesc>
                  <p>A parchment roll of 18 membranes.</p>
               </physDesc>
               <history>
                  <origin>
                     <p>Probably drawn up in Ireland and despatched to Westminster, England, for an
                        audit of the accounts of the treasurer of the Irish Exchequer</p>
                  </origin>
               </history>
            </msDesc>
         </sourceDesc>
```

If we are creating TEI/XML from a pre-1922 calendar or transcript, I expect we will want to record the details of what is known about the lost manuscript and the details of the calendar/transcript.

Interestingly, the Henry III fine rolls says:

```
<p>No source: created in electronic format.</p>
```
I don't agree since they are using a source manuscript.

**Comment by crooksp** [comment]
I would agree with you Mike!

**Comment by munnellg** [comment]
I think my answer to Issue #15 is relevant here too. If we were to store this relationship in the DB it would depend on whether or not the source existed in the database.

If it exists in the DB, we can use the reference code to find it and create a link

If it doesn't exist, then we want a URL such as the DOI which we can use to link out to it.

**Comment by MikeJ1971** [comment]
Get rid of history.

**Comment by MikeJ1971** [comment]
Would the TNA permalink be enough?

```
<msDesc>
               <msIdentifier>
                  <settlement>London</settlement>
                  <repository>The National Archives</repository>
                  <idno>E 101/233/16</idno>
                  <idno type="URI">https://discovery.nationalarchives.gov.uk/details/r/C4513834</idno>
                  <msName>Roll of receipts. 29 and 30 Edward I.</msName>
               </msIdentifier>
               <msContents>
                  <textLang mainLang="la">Latin</textLang>
               </msContents>
               <physDesc>
                  <p>A parchment roll of 18 membranes.</p>
               </physDesc>
            </msDesc>
```

**Comment by MikeJ1971** [comment]
Added in the MARC reference:

```
<idno type="MARC">UK-KeNA E 101/233/16</idno>
```
