### ISSUE TITLE
Notes on contains information about the creation of a text.

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#13]
The 'creation' element contains information about the creation of the text. This is taken as the original manuscript text, not the TEI document. This is certainly the approach taken in MPESE:

```
<creation>
    <date when="1627-11-22">22 November 1627</date>
    <placeName corresp="../places/places.xml#PL0010">Court of King's Bench</placeName>
</creation>
```

For the 1301/2 receipt roll, I've put the Exchequer Term as as date range:

```
<creation>
    <date from="1301-09-30" to="1302-09-29">30 September 1301 to 29 September 1302</date>
</creation>
```

The text between the <date> tags can be in any format, but we should use the @when attribute that uses the format YYYY-MM-DD, YYYY-MM and YYYY. 

See https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-creation.html
See https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-date.html

I need to revisit this to provide better guidance on uncertainty and calendars – in the early modern period we are going to be dealing with Julian and Gregorian calendars.

**Comment by crooksp** [comment]
I'd agree that this refers to the original manuscript and it's content date-range

**Comment by MikeJ1971** [comment]
Nothing controversion here. Keeping the example and closing the ticket.
