### ISSUE TITLE
Library of Congress keywords

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#14]
I understand that Peter would like to use the Library of Congress subject heading:  https://id.loc.gov/authorities/subjects.html

I've used the textClass, keywords and term elements:

```
         <textClass>
            <keywords scheme="http://id.loc.gov/authorities/subjects.html">
               <term ref="http://id.loc.gov/authorities/subjects/sh85067964">Ireland</term>
               <term ref="http://id.loc.gov/authorities/subjects/sh85085001">Middle Ages</term>
               <term ref="http://id.loc.gov/authorities/subjects/sh85048256">Finance</term>
               <term ref="http://id.loc.gov/authorities/subjects/sh85048326">Fines and
                  Recoveries</term>
            </keywords>
         </textClass>
```

See https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-textClass.html
See https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-keywords.html
See https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-term.html

**Comment by MikeJ1971** [comment]
With regard to compatibility with the infrastructure being developed at Trinity, I've asked the following questions:

`Am I correct in thinking that the ‘compatibility’ between the TEI files and both the knowledge base and the database is just the case of ensuring that the same taxonomy terms are used?`

`Even if the TEI XML files are not stored in the database itself as BLOBs (or whatever) there will be a row in the database that will contain metadata about the file, including keywords? What metadata is needed? Can I/we write an XQuery script to extract the data from the XML file that is needed in the database?`

**Comment by MikeJ1971** [comment]
So, we should be using FAST LoC headings (https://fast.oclc.org/searchfast/) here as well?

**Comment by munnellg** [comment]
That would be my intention, yes.

**Comment by crooksp** [comment]
@munnellg can you clarify for Mike what type of link we should encode. It looks to me like the LoC headings can be output in a number of different formats. Would we want a WorldCat permalink such as this: http://id.worldcat.org/fast/946068/ 

Or Would we want the RDF view: http://id.worldcat.org/fast/946068.rdf.xml

Or does it make any difference? 

Declan O'Sullivan's advice was definitely to include the link, but I'm not sure what format would be preferable to future proof this approach to topical keywords. 

Bear in mind that the keywords may prove useful for the IR.

**Comment by munnellg** [comment]
I think the link for the RDF view would be preferable, especially if we want to be able to process whatever is on the other end of the link.

**Comment by crooksp** [comment]
that makes sense to me. it's precisely the question about being able to
process -- and what and how we want to process - - that I'm getting at.

**Comment by MikeJ1971** [comment]
Updated to use https://fast.oclc.org/searchfast/ with the **@ref** pointing to the RDF version.

```
         <!-- searchFast: https://fast.oclc.org/searchfast/ -->
         <textClass>
            <keywords scheme="https://fast.oclc.org/">
               <term ref="http://id.worldcat.org/fast/1205427.rdf.xml">Ireland</term>
               <term ref="http://id.worldcat.org/fast/1020301.rdf.xml">Middle Ages</term>
               <term ref="http://id.worldcat.org/fast/924349.rdf.xml">Finance</term>
               <term ref="http://id.worldcat.org/fast/924841.rdf.xml">Fines and
                  Recoveries</term>
            </keywords>
         </textClass>
      </profileDesc>
```
