### ISSUE TITLE
Is the title sufficient for the database?

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#16]
Is the title provided in the file description sufficient for the database?

```
<title>Receipt Roll of the Irish Exchequer for 29 and 30 Edward I (The National Archives, E 101)</title>
```

This is an XPath query to get the database. We normalize the space as the title might be wrapped over several lines:

```
//teiHeader/fileDesc/titleStmt/title/normalize-space(text())
```

**Comment by crooksp** [comment]
yes that will work

**Comment by pdryburgh** [comment]
Would we not what the full document reference here, not simply "E 101"?

<title>Receipt Roll of the Irish Exchequer for 29 and 30 Edward I (The National Archives, E 101/233/16)</title>

**Comment by MikeJ1971** [comment]
I'll update the example.

**Comment by MikeJ1971** [comment]
Example updated.
