### ISSUE TITLE
Is the idno sufficient for the unique reference code for the database?

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#17]
For the identifier, I've put the call number used by The National Archives. Is this sufficient for the database 'unique reference number'? I'm guessing so if we are talking about the 'Reference code' described in ISAD(G).

```
<idno>E 101/233/16</idno>
```

XPath:

```
normalize-space(//teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/idno/string())
```

Value:

```
E 101/233/16
```

I suppose we might have a clash if two repositories use the same identifier. We might want to include the archive with the identifier.

XPath:

```
normalize-space(concat(//teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/repository/string(), ', ', //teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/idno/string()))
```

Output:

```
The National Archives, E 101/233/16
```

**Comment by crooksp** [comment]
The reference code will need to include the repository to be unique using the MARC identifier for the national archives uk

**Comment by pdryburgh** [comment]
TNA's international archive code is GBR066. That should perhaps be included too.

**Comment by munnellg** [comment]
As Peter says, MARC code plus the Reference Code will do the job.

**Comment by MikeJ1971** [comment]
Looking at the comments and my rough notes from the meeting, I'm now a bit confused. I've updated the <msIdentifier/> section so that we have:

```
            <msDesc>
               <msIdentifier>
                  <settlement>London</settlement>
                  <repository>The National Archives</repository>
                  <idno>E 101/233/16</idno>
                  <idno type="URI">https://discovery.nationalarchives.gov.uk/details/r/C4513834</idno>
                  <msName>Roll of receipts. 29 and 30 Edward I.</msName>
               </msIdentifier>
               <msContents>
                  <textLang mainLang="la">Latin</textLang>
               </msContents>
               <physDesc>
                  <p>A parchment roll of 18 membranes.</p>
               </physDesc>
            </msDesc>
```

Is this ok? This gives the repository and the call number used by that repository. I've also added the TNA discovery permalink as second ID.

**Comment by crooksp** [comment]
Thanks Mike -- is there another (additional) tag that could be used to represented the unique ID for the repository? The MARC code for The National Archives is "UK-KeNA". 

When it comes to the associated digital images, we will be concatenating the Repository and Reference Code to make the string for each set of images unique, e.g. UK-KeNA E 101/233/16.

**Comment by MikeJ1971** [comment]
Ah! I finally understand! How about:

```
<idno type="MARC">UK-KeNA E 101/233/16</idno>
```

So we have

```
               <msIdentifier>
                  <settlement>London</settlement>
                  <repository>The National Archives</repository>
                  <idno>E 101/233/16</idno>
                  <idno type="MARC">UK-KeNA E 101/233/16</idno>
                  <idno type="URI">https://discovery.nationalarchives.gov.uk/details/r/C4513834</idno>
                  <msName>Roll of receipts. 29 and 30 Edward I.</msName>
               </msIdentifier>
```

**Comment by munnellg** [comment]
Can I suggest type="b2022-idno"? The example isn't a MARC code and might be misleading if someone with no knowledge of the project is trying to interpret it.

Pure pedantry, but I think it makes more sense, unless the value of type is restricted to a list of values?

**Comment by MikeJ1971** [comment]
Ok. Updated the example to use the attribute you suggested.
