### ISSUE TITLE
Is the knowledge graph only concerned with people and places?

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#19]
A question I asked on email:

```
Is the Beyond2022 knowledge focussed on people and places? Will it cover other concepts?
I can see from the partial dataset you provided there are events but are related to the birth and death of individuals. 
```

Using the text classification element, we can link to an object in the graph:

```
         <textClass>
            <keywords scheme="http://ont.beyond2022.ie/ontology#">
               <term ref="https://kb.beyond2022.ie/person/615_-_0000_g>">Edward I</term>
            </keywords>
         </textClass>
```

The @ref attribute is the URI and the string is from an rdfs:label from an appropriate object linked to that URI.

**Comment by crooksp** [comment]
hi Mike, 

People, Places and Organizations/Offices: the Beyond 2022 ontology would permit us to encode, say, "sheriff of Meath", which is an office (sheriff) for a place (the medieval shire of Meath). 

Peter

**Comment by MikeJ1971** [comment]
Thanks for the clarification.
