### ISSUE TITLE
Who do we mention in the 'responsibility' section?

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#2]
At this point, you could mention anyone involved in the project at all. However, do we just want to record who was immediately involved in the preparation of the text and its editing? Basically, whoever created the translation and transcription and who proofread it for errors?

See https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-respStmt.html

**Comment by pdryburgh** [comment]
For our project, I guess the main individual responsible will be the editor but for other seams, as yet unplanned, there may be different circumstances.

**Comment by MikeJ1971** [comment]
Limit to direct editorial involvement in the document.

**Comment by MikeJ1971** [comment]
I've updated to include those involved with the editorial decisions on the text, including Brendan who will be involved later. I've just put a simple responsibility statement as 'editor'

```
            <respStmt xml:id="peter-crooks">
               <name>Peter Crooks</name>
               <resp>editor</resp>
            </respStmt>
            <respStmt xml:id="paul-dryburgh">
               <name>Paul Dryburgh</name>
               <resp>editor</resp>
            </respStmt>
            <respStmt xml:id="lynn-kilgannon">
               <name>Lynn Kilgannon</name>
               <resp>editor</resp>
            </respStmt>
            <respStmt xml:id="elizabeth-biggs">
               <name>Elizabeth Biggs</name>
               <resp>editor</resp>
            </respStmt>
            <respStmt xml:id="mike-jones">
               <name>Mike Jones</name>
               <resp>editor</resp>
            </respStmt>
            <respStmt xml:id="brendan-smith">
               <name>Brendan Smith</name>
               <resp>editor</resp>
            </respStmt>
```
