### ISSUE TITLE
Should we use the UK TNA taxonomy?

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#21]
I extracted the terms used in the TNA taxonomy from the Discovery search form:

https://github.com/ilrt/Beyond2022TeiTemplate/blob/master/taxonomies/tna_discovery.csv

I've included the use of the taxonomy as an example?

         ```
         <textClass>
            <keywords scheme="http://discovery.nationalarchives.gov.uk/">
               <term>Ireland</term>
            </keywords>
         </textClass>
         ```

Should we use it? Will Discovery be incorporating Beyond 2022 data in the future? Are these covered in the Library of Congress subject headings.

**Comment by crooksp** [comment]
hi Mike, 

I have spoken to the Beyond 2022 team and we would like to recommend using FAST LoC headings. 

https://fast.oclc.org/searchfast/

Peter

**Comment by MikeJ1971** [comment]
Remove the TNA taxonomy from the example.

**Comment by MikeJ1971** [comment]
The example has been updated with the taxonomy removed.
