### ISSUE TITLE
Convention for XML IDs that represent people?

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#3]
It is useful to give responsibility statements an XML ID. For example,

```
            <respStmt xml:id="PC">
               <name>Peter Crooks</name>
               <resp>Programme Director</resp>
            </respStmt>
```
So that it can be referenced elsewhere in the document. For example, if we record changes made to the document by that person (see the @resp attribute):

```
<change status="draft" when="2020-08-01" resp="#PD">Initial draft</change>
```

In the initial example, I've only use first and last name initials. But we need something that doesn't clash.

**Comment by pdryburgh** [comment]
That seems useful to me as an internal audit trail if nothing else.

**Comment by munnellg** [comment]
Would it be helpful if the ids in the reference statements matched the usernames in the B2022 data capture interface? They'll be unique and it means that the activities of the individual can be seen in the database too.

**Comment by pdryburgh** [comment]
That sounds like a great way to go, yes.

**Comment by crooksp** [comment]
> Would it be helpful if the ids in the reference statements matched the usernames in the B2022 data capture interface? They'll be unique and it means that the activities of the individual can be seen in the database too.

just to check -- are the B2022 IDs human interpretable? The principle you are outlining here gary works well

**Comment by munnellg** [comment]
Reasonably human interpretable. We haven't exactly standardised the format. I used college usernames and Darragh has been using forename-surname?

So we can definitely make them human intelligible.

**Comment by MikeJ1971** [comment]
We might also need some to disambiguate names? _Mike Jones_ is a very common name in England. Also, if we are using for XML:id, they can't start with a number etc.

**Comment by munnellg** [comment]
I suppose I'm thinking specifically within the project. If we had two Mike Jones, then the DB usernames would be something like mikejones and mikejones1. Should still work for the XML id. Could also use middle initial do disambiguate?

**Comment by MikeJ1971** [comment]
Ok. I've gone with firstname-lastname. We can change these later if needed.

```
            <respStmt xml:id="peter-crooks">
               <name>Peter Crooks</name>
               <resp>editor</resp>
            </respStmt>
            <respStmt xml:id="paul-dryburgh">
               <name>Paul Dryburgh</name>
               <resp>editor</resp>
            </respStmt>
            <respStmt xml:id="lynn-kilgannon">
               <name>Lynn Kilgannon</name>
               <resp>editor</resp>
            </respStmt>
            <respStmt xml:id="elizabeth-biggs">
               <name>Elizabeth Biggs</name>
               <resp>editor</resp>
            </respStmt>
            <respStmt xml:id="mike-jones">
               <name>Mike Jones</name>
               <resp>editor</resp>
            </respStmt>
            <respStmt xml:id="brendan-smith">
               <name>Brendan Smith</name>
               <resp>editor</resp>
            </respStmt>
```
