### ISSUE TITLE
Who is the publisher?

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#5]
Who will be the publisher of the documents? The project? Trinity College Dublin?

See https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-publisher.html

**Comment by crooksp** [comment]
Trinity College Dublin, The University of Dublin

**Comment by MikeJ1971** [comment]
Ok. We now have:

```
<publisher>Trinity College Dublin, The University of Dublin</publisher>
```
I'll close the ticket and remove the link to the ticket from the source.
