### ISSUE TITLE
What licence will the TEI/XML be made available under?

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#6]
Under what licence are the documents going to be released under? A creative commons one? As an example, I've used 'Creative Common Attribution-ShareAlike'

```
<licence target="https://creativecommons.org/licenses/by-sa/4.0/">Creative Common Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)</licence>
```

See https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-licence.html

**Comment by crooksp** [comment]
This is fine for the purposes of example

**Comment by MikeJ1971** [comment]
Still to be decided. Use creative commons as a placeholder for the moment.
