### ISSUE TITLE
Shall we record if the document is part of series?

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#7]
We can record that a record is a part of a series in a <seriesStmt> (series statement) element: "(series statement) groups information about the series, if any, to which a publication belongs"

Do we want to record the document series? For example:

```
         <seriesStmt>
            <title>Receipt Rolls of the Irish Exchequer (The National Archives, E 101).</title>
            <idno>E 101</idno>
         </seriesStmt>
```

Or that this is part of the Medieval Gold Seam?

```
         <seriesStmt>
               <p>Receipt Rolls of the Irish Exchequer (The National Archives, E 101). Part of the 
                      Beyond 2022 Medieval Gold Seam.</p>
         </seriesStmt>
```

See https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-seriesStmt.html

**Comment by crooksp** [comment]
Unsure -- could this be used to refer to the series destroyed in PROI in 1922?

**Comment by munnellg** [comment]
The first option seems more useful to me than the second. I can't see how you would use the second option to insert the item into an ISAD(G) hierarchy, but the first explicitly calls out the ID and title of the parent.

In truth, when identifying the parent, we'll ignore the title and just search using the idno.

**Comment by MikeJ1971** [comment]
Ok, I'll leave it with the original example and will close the ticket. We can review if we find this information isn't useful or what we want to represent.
