### ISSUE TITLE
What information should we give for the project description?

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#8]
The 'project description' element, found under the 'encoding description' allows the opportunity to document 'the relationship between an electronic text and the source or sources from which it was derived'. I've used it to describe that this work is part of the Medieval Gold Seam:

```
      <encodingDesc>
         <projectDesc>
            <p>Created as part of the Medieval Gold Seam of the Beyond 2022 project.</p>
         </projectDesc>
      </encodingDesc>
```

Is this ok?  Do we want a more generic description about Beyond 2022?

See https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-encodingDesc.html

**Comment by crooksp** [comment]
Yes that's fine -- do we give dates of the project?

**Comment by MikeJ1971** [comment]
We can do. In this seam, is that 2020 – 2022?

**Comment by crooksp** [comment]
2019-23

**Comment by crooksp** [comment]
@crooksp give Mike the detail

**Comment by crooksp** [comment]
Created as part of the Medieval Gold Seam of the 'Beyond 2022: Ireland's Virtual Record Treasury' Research Project, Phase 2 (2019–22)

**Comment by MikeJ1971** [comment]
Updated with text provided by Peter. Closing ticket.
