### ISSUE TITLE
How specific should the information be in the 'editorial practice declaration'?

### ISSUE THREAD

**Issue by MikeJ1971** [ilrt/Beyond2022TeiTemplate#9]
We can give an 'editorial practice declaration' that 'provides details of editorial principles and practices applied during the encoding of a text'. 

In the following example, I lifted part of Paul's style guide regarding the Irish Exchequer Receipt Rolls. Should we have a very general declaration for all document, or provide a more specific one for the document series. The latter since more helpful since some might be straight English translations while others are abstracts.

```
         <editorialDecl>
            <p>The guiding principle is to make this edition of the accounts of the medieval Irish
               Exchequer (and other medieval records populating Beyond 2022 Virtual Record Treasury)
               as intelligible as possible to as wide an audience as possible. To that end, due to
               their generally brief, formulaic nature the records are more or less directly
               translated into modern English without losing the literal, technical sense of the
               original language, which is almost exclusively Latin.</p>
         </editorialDecl>
```

See https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-editorialDecl.html

**Comment by crooksp** [comment]
I think we should think about the possible uses we put the TEI to across B2022. 

For this series, we are providing a translation, but elsewhere it could be a diplomatic edition, summary calendar, listing etc.

**Comment by MikeJ1971** [comment]
It should be specific at least to each gold seam, but can be specific to the document and series it is from.
